// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'neutral2': string;
  'neutral4': string;
  'neutral6': string;
  'neutral8': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
